name: shrm_homework_app
description: "financial app for shmr"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.1.0
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  auto_route: ^10.1.0+1

dev_dependencies:
  auto_route_generator: 10.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  freezed: ^3.0.6


flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
