name: shrm_homework_app
description: "financial app for shmr"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.2.0
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  auto_route: ^10.1.0+1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.34
  sqlite3: ^2.7.6
  path: ^1.9.1
  fuzzywuzzy: ^1.2.0
  talker_flutter: ^4.9.1
  talker_bloc_logger: ^4.9.1

dev_dependencies:
  auto_route_generator: 10.2.3
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  freezed: ^3.0.6
  drift_dev: ^2.27.0


flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
