name: shrm_homework_app
description: "financial app for shmr"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  transaction_chart:
    path: ./transaction_chart
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.2.0
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  auto_route: ^10.1.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.34
  sqlite3: ^2.7.6
  path: ^1.9.1
  fuzzywuzzy: ^1.2.0
  talker_flutter: ^4.9.1
  talker_bloc_logger: ^4.9.1
  fuzzy: ^0.5.1
  intl: ^0.19.0  
  fl_chart: ^1.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  retry: ^3.1.2
  json_annotation: ^4.9.0
  worker_manager: ^7.2.6
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.0.0
  secure_application: ^4.1.0
  local_auth: ^2.3.0
  envied: ^1.1.1


dev_dependencies:
  auto_route_generator: 10.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  freezed: ^3.0.6
  drift_dev: ^2.27.0
  flutter_gen_runner: ^5.4.0
  envied_generator: ^1.1.1  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/app/
  
flutter_intl:  
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-localization-file: l10n.dart
  preferred-supported-locales:
    - en
    - ru

flutter_native_splash:
  color: "#ffffff"
  image: assets/app/splash_icon.png
  branding: assets/app/splash_icon.png
  color_dark: "#ffffff"
  image_dark: assets/app/splash_icon.png
  branding_dark: assets/app/splash_icon.png
  
  android_12:
    image: assets/app/splash_icon.png
    color: "#ffffff"
    image_dark: assets/app/splash_icon.png
    color_dark: "#ffffff"
  
  web: false
  ios: true
  android: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
